{% set name = "hookee" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8354b603c6310c5cb9021115de9785854783977363e8f8686e181b76e85a4c8b

build:
  noarch: python
  entry_points:
    - hookee=hookee.cli:hookee
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - pluginbase
    - confuse
    - python-dotenv
    - flask
    - click
    - pyngrok

test:
  imports:
    - hookee
  commands:
    - pip check
    - hookee --help
  requires:
    - pip

about:
  home: https://github.com/alexdlaird/hookee
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line webhooks, on demand
  description: |
    hookee is a utility that provides command line webhooks, on demand! Dump useful request data to the
    console, process requests and responses, customize response data, and configure hookee and its routes
    further in any number of ways through custom plugins.
  dev_url: https://github.com/alexdlaird/hookee

extra:
  recipe-maintainers:
    - alexdlaird
