{% set name = "hookee" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c7c0adc9b2422823556a596c383181e81f162f80eb0c061c247569747722b90

build:
  noarch: python
  entry_points:
    - hookee=hookee.cli:hookee
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pluginbase
    - confuse
    - flask >=1.1.0,<2.0.0
    - click
    - pyngrok >=5.2.3
    - defusedxml
    # Remove these pinned deps once hookee is updated to work with Flask 2.x
    - MarkupSafe >=0.23,<2.1.0
    - Jinja2 <3.0,>=2.10.1
    - itsdangerous ==2.0.1
    - werkzeug ==2.0.3

test:
  imports:
    - hookee
  commands:
    - pip check
    - hookee --help
  requires:
    - pip

about:
  home: https://github.com/alexdlaird/hookee
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line webhooks, on demand
  description: |
    hookee is a utility that provides command line webhooks, on demand! Dump useful request data to the
    console, process requests and responses, customize response data, and configure hookee and its routes
    further in any number of ways through custom plugins.
  dev_url: https://github.com/alexdlaird/hookee

extra:
  recipe-maintainers:
    - alexdlaird
