{% set name = "hookee" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: becbb0e2db41ea87ead2e2eb330f1b4c1a232f6ce08a016854cb1be5e964ef80

build:
  noarch: python
  entry_points:
    - hookee=hookee.cli:hookee
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - pyngrok
    - python-dotenv
    - flask

test:
  imports:
    - hookee
  commands:
    - pip check
    - hookee --help
  requires:
    - pip

about:
  home: https://github.com/alexdlaird/hookee
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line webhooks, on demand
  description: |
    hookee is a simple command line utility which generates webhooks on demand and dumps useful information
    to the console when requests are sent to those endpoints.
  dev_url: https://github.com/alexdlaird/hookee

extra:
  recipe-maintainers:
    - alexdlaird
